# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-29 02:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produce', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typemodel',
            options={'verbose_name': '类型', 'verbose_name_plural': '类型'},
        ),
    ]
