# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-29 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produce', '0002_auto_20190329_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typemodel',
            name='image',
            field=models.ImageField(upload_to='media/first_chart/', verbose_name='类型封面图'),
        ),
    ]
