# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-29 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produce', '0003_auto_20190329_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typemodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='类型名字'),
        ),
    ]
