# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-29 03:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produce', '0004_auto_20190329_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='文章标题')),
                ('image', models.ImageField(upload_to='media/content_chart/', verbose_name='文章配图')),
                ('path', models.CharField(max_length=1000, verbose_name='文章对应的链接')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='produce.TypeModel', verbose_name='关联的类型')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
    ]
