# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-29 07:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produce', '0005_typecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typecontent',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='produce.TypeModel', verbose_name='关联的类型'),
        ),
    ]
